export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const GET_HIGHEST_RATING_PRODUCT = 'GET_HIGHEST_RATING_PRODUCT';
export const GET_HIGHEST_RATING_PRODUCT_SUCCESSFULLY = 'GET_HIGHEST_RATING_PRODUCT_SUCCESSFULLY';
export const GET_HIGHEST_RATING_PRODUCT_FAILED = 'GET_HIGHEST_RATING_PRODUCT_FAILED';

export const SAVE_JUDGE_FOR_PRODUCT = 'SAVE_JUDGE_FOR_PRODUCT';
export const SAVE_JUDGE_FOR_PRODUCT_SUCCESSFULLY = 'SAVE_JUDGE_FOR_PRODUCT_SUCCESSFULLY';
export const SAVE_JUDGE_FOR_PRODUCT_FAILED = 'SAVE_JUDGE_FOR_PRODUCT_FAILED';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET'

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET'

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'



export const TYPE_CREATE_REQUEST = 'TYPE_CREATE_REQUEST'
export const TYPE_CREATE_SUCCESS = 'TYPE_CREATE_SUCCESS'
export const TYPE_CREATE_FAIL = 'TYPE_CREATE_FAIL'
export const TYPE_CREATE_RESET = 'TYPE_CREATE_RESET'

export const TYPE_UPDATE_REQUEST = 'TYPE_UPDATE_REQUEST'
export const TYPE_UPDATE_SUCCESS = 'TYPE_UPDATE_SUCCESS'
export const TYPE_UPDATE_FAIL = 'TYPE_UPDATE_FAIL'
export const TYPE_UPDATE_RESET = 'TYPE_UPDATE_RESET'

export const TYPE_LIST_REQUEST = 'TYPE_LIST_REQUEST'
export const TYPE_LIST_SUCCESS = 'TYPE_LIST_SUCCESS'
export const TYPE_LIST_FAIL = 'TYPE_LIST_FAIL'

export const TYPE_DETAILS_REQUEST = 'TYPE_DETAILS_REQUEST'
export const TYPE_DETAILS_SUCCESS = 'TYPE_DETAILS_SUCCESS'
export const TYPE_DETAILS_FAIL = 'TYPE_DETAILS_FAIL'