export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USERS_ARE_BEING_LOADED = 'USERS_ARE_BEING_LOADED';
export const USERS_HAVE_BEEN_LOADED = 'USERS_HAVE_BEEN_LOADED';

export const USERS_RELATED_TO_PRODUCT_REQUEST = 'USERS_RELATED_TO_PRODUCT_REQUEST';
export const USERS_RELATED_TO_PRODUCT_REQUEST_SUCCESSFULLY = 'USERS_RELATED_TO_PRODUCT_REQUEST_SUCCESSFULLY';
export const USERS_RELATED_TO_PRODUCT_REQUEST_FAILED = 'USERS_RELATED_TO_PRODUCT_REQUEST_FAILED';

export const USERS_RELATED_TO_PRODUCT_ARE_BEING_LOADED = 'USERS_RELATED_TO_PRODUCT_ARE_BEING_LOADED';
export const USERS_RELATED_TO_PRODUCT_HAVE_BEEN_LOADED = 'USERS_RELATED_TO_PRODUCT_HAVE_BEEN_LOADEDE_BEEN_LOADED';
export const USERS_RELATED_TO_PRODUCT_NEED_TO_BE_RELOADED = 'USERS_RELATED_TO_PRODUCT_NEED_TO_BE_RELOADED';